USE nism;
SET SQL_SAFE_UPDATES = 0;
UPDATE nism.device SET province_id = 285 WHERE province_name = 'Sơn La';
UPDATE nism.device SET province_id = 287 WHERE province_name = 'Tuyên Quang';
UPDATE nism.device SET province_id = 288 WHERE province_name = 'Thái Bình';
UPDATE nism.device SET province_id = 289 WHERE province_name = 'Thanh Hóa';
UPDATE nism.device SET province_id = 290 WHERE province_name = 'Thái Nguyên';
UPDATE nism.device SET province_id = 291 WHERE province_name = 'Vĩnh Phúc';
UPDATE nism.device SET province_id = 292 WHERE province_name = 'Hà Nội';
UPDATE nism.device SET province_id = 293 WHERE province_name = 'Bắc Giang';
UPDATE nism.device SET province_id = 294 WHERE province_name = 'Bắc Ninh';
UPDATE nism.device SET province_id = 295 WHERE province_name = 'Bắc Kạn';
UPDATE nism.device SET province_id = 296 WHERE province_name = 'Cao Bằng';
UPDATE nism.device SET province_id = 297 WHERE province_name = 'Hòa Bình';
UPDATE nism.device SET province_id = 298 WHERE province_name = 'Hà Giang';
UPDATE nism.device SET province_id = 299 WHERE province_name = 'Hải Phòng';
UPDATE nism.device SET province_id = 300 WHERE province_name = 'Hà Tĩnh';
UPDATE nism.device SET province_id = 301 WHERE province_name = 'Hải Dương';
UPDATE nism.device SET province_id = 302 WHERE province_name = 'Hưng Yên';
UPDATE nism.device SET province_id = 303 WHERE province_name = 'Lào Cai';
UPDATE nism.device SET province_id = 304 WHERE province_name = 'Lai Châu';
UPDATE nism.device SET province_id = 305 WHERE province_name = 'Lạng Sơn';
UPDATE nism.device SET province_id = 306 WHERE province_name = 'Ninh Bình';
UPDATE nism.device SET province_id = 307 WHERE province_name = 'Nghệ An';
UPDATE nism.device SET province_id = 308 WHERE province_name = 'Nam Định';
UPDATE nism.device SET province_id = 309 WHERE province_name = 'Hà Nam';
UPDATE nism.device SET province_id = 310 WHERE province_name = 'Phú Thọ';
UPDATE nism.device SET province_id = 311 WHERE province_name = 'Quảng Ninh';
UPDATE nism.device SET province_id = 312 WHERE province_name = 'Quảng Bình';
UPDATE nism.device SET province_id = 313 WHERE province_name = 'Điện Biên';
UPDATE nism.device SET province_id = 314 WHERE province_name = 'Yên Bái';
UPDATE nism.device SET province_id = 315 WHERE province_name = 'Đà Nẵng';
UPDATE nism.device SET province_id = 316 WHERE province_name = 'Quảng Trị';
UPDATE nism.device SET province_id = 318 WHERE province_name = 'Quảng Ngãi';
UPDATE nism.device SET province_id = 319 WHERE province_name = 'Quảng Nam';
UPDATE nism.device SET province_id = 320 WHERE province_name = 'Thừa Thiên Huế';
UPDATE nism.device SET province_id = 321 WHERE province_name = 'Đắk Lắk';
UPDATE nism.device SET province_id = 322 WHERE province_name = 'Bình Định';
UPDATE nism.device SET province_id = 323 WHERE province_name = 'Bình Thuận';
UPDATE nism.device SET province_id = 324 WHERE province_name = 'Gia Lai';
UPDATE nism.device SET province_id = 325 WHERE province_name = 'Khánh Hòa';
UPDATE nism.device SET province_id = 326 WHERE province_name = 'Kon Tum';
UPDATE nism.device SET province_id = 327 WHERE province_name = 'Lâm Đồng';
UPDATE nism.device SET province_id = 328 WHERE province_name = 'Ninh Thuận';
UPDATE nism.device SET province_id = 329 WHERE province_name = 'Phú Yên';
UPDATE nism.device SET province_id = 330 WHERE province_name = 'Đắk Nông';
UPDATE nism.device SET province_id = 332 WHERE province_name = 'An Giang';
UPDATE nism.device SET province_id = 334 WHERE province_name = 'Tây Ninh';
UPDATE nism.device SET province_id = 335 WHERE province_name = 'Tiền Giang';
UPDATE nism.device SET province_id = 341 WHERE province_name = 'Bến Tre';
UPDATE nism.device SET province_id = 343 WHERE province_name = 'Bình Phước';
UPDATE nism.device SET province_id = 344 WHERE province_name = 'Bạc Liêu';
UPDATE nism.device SET province_id = 346 WHERE province_name = 'Cà Mau';
UPDATE nism.device SET province_id = 349 WHERE province_name = 'Long An';
UPDATE nism.device SET province_id = 355 WHERE province_name = 'Trà Vinh';
UPDATE nism.device SET province_id = 361 WHERE province_name = 'Bình Dương';
UPDATE nism.device SET province_id = 364 WHERE province_name = 'Cần Thơ';
UPDATE nism.device SET province_id = 366 WHERE province_name = 'TPHCM';
UPDATE nism.device SET province_id = 367 WHERE province_name = 'Kiên Giang';
UPDATE nism.device SET province_id = 369 WHERE province_name = 'Hậu Giang';
UPDATE nism.device SET province_id = 374 WHERE province_name = 'Sóc Trăng';
UPDATE nism.device SET province_id = 378 WHERE province_name = 'Bà Rịa Vũng Tàu';
UPDATE nism.device SET province_id = 379 WHERE province_name = 'Vĩnh Long';
UPDATE nism.device SET province_id = 380 WHERE province_name = 'Đồng Nai';
UPDATE nism.device SET province_id = 381 WHERE province_name = 'Đồng Tháp';
UPDATE nism.device SET province_id = 15801 WHERE province_name = 'Tỉnh test pp11';
UPDATE nism.device SET province_id = 1002647 WHERE province_name = 'Tỉnh hai';
UPDATE nism.device SET province_id = 1002648 WHERE province_name = 'Tỉnh Hai';
UPDATE nism.device SET province_id = 1002777 WHERE province_name = 'hongptt2';
UPDATE nism.device SET province_id = 1002786 WHERE province_name = 'TEST HANH';
UPDATE nism.device SET province_id = 1002797 WHERE province_name = 'Test TH111';
UPDATE nism.device SET province_id = 1002908 WHERE province_name = 'PXC4';
UPDATE nism.device SET province_id = 1010861 WHERE province_name = 'LIMA';
UPDATE nism.device SET province_id = 1010862 WHERE province_name = 'HNI';
